---
title: "Preparation"
author: "Tillmann Schwörer"
date: "WS 2020/21"
output: 
  html_document:
    toc: true
    toc_float: true
    df_print: paged
    code_folding: show  
    highlight: tango
    number_sections: true
---

```{r}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, fig.height = 5, fig.width = 12)
```

# Packages
```{r}
library(tidyverse)
library(sf)
library(tmap)
library(osmdata)
library(RANN)
```

# Read data
```{r}
load("rdata/rawdata.Rdat")
```

# Functions
```{r}
polygons_to_points <- function(osm){
  points <- osm[["osm_points"]]           
  polygons <- osm[["osm_polygons"]]
  points_not_covered <- points[!lengths(st_intersects(points, polygons)), ]
  polygons_centroids <- polygons %>% st_centroid()
  bind_rows(points_not_covered, polygons_centroids)
}
```

# Airbnb
```{r}
airbnb <- airbnb_raw %>% 
  select(id, listing_url, amenities, host_response_time, neighbourhood_cleansed,
         neighbourhood_group_cleansed, latitude, longitude, property_type, room_type, 
         accommodates, bathrooms, bedrooms, beds, price, number_of_reviews, 
         review_scores_rating) %>% 
  mutate(wifi = str_detect(amenities, "Wifi"),
        tv = str_detect(amenities, "TV"),
        bed_linens = str_detect(amenities, "Bed linens"),
        parking = str_detect(amenities, "parking"),
        garden = str_detect(amenities, "Garden")) %>%
  mutate(price = as.numeric(str_sub(price, 2))) %>%
  st_as_sf(coords = c("longitude", "latitude"), crs = 4326, agr = "constant")


```

## Select feature type
```{r}
districts <- districts_raw$osm_multipolygons %>% select(name)
stops <- stops_raw$osm_points %>% filter(railway %in% c("stop","tram_stop")) 
restaurants <- polygons_to_points(osm = restaurants_raw) 

```

## Joins
```{r}
df <- airbnb
```

### Districts
```{r}
df <- df %>% st_join(districts, join = st_covered_by)  # Which district covers an airbnb object?
```

### Restaurants
What are the number of restaurants within radius around airbnb object?

```{r}
airbnb <- airbnb %>% st_transform(3035)
restaurants <- restaurants %>% st_transform(3035)

# Get coordinates of restaurants and airbnb objcts
coord_airbnb <- st_coordinates(airbnb$geometry)
coord_restaurants <- st_coordinates(restaurants$geometry)
str(coord_airbnb)

# Get Restaurants within 300m radius
radius_restaurants <- nn2(data = coord_restaurants, query = coord_airbnb, k = 500, searchtype = "radius", radius = 300, eps = 0.0)

# Count restaurants and add to data
df <- df %>% mutate(n_restaurants = rowSums(radius_restaurants$nn.idx>0))
```

### Stops
```{r}
stop_distances <- nngeo::st_nn(df, stops, maxdist = 15000, k = 1, returnDist = TRUE)
df <- df %>% mutate(stop_dist = round(as.numeric(stop_distances$dist)))
```

### Parks
```{r}
tmap_mode("view")
forest_raw$osm_polygons %>% tm_shape() + tm_fill("black")
forest_test %>% tm_shape() + tm_fill("black")


forest_area <- forest_raw$osm_polygons %>% st_area()
forest_large <- forest_raw$osm_polygons[forest_area > units::set_units(1000000, m^2), ]

# Visualization
nearest_forest <- nngeo::st_nn(df[1:10,], forest_large, maxdist = 10000, k = 1, returnDist = FALSE)
nearest_forest_connect <- nngeo::st_connect(df[1:10,], forest_large, ids = bla)
tmap_mode("view")
tm_shape(forest_large) + tm_fill("darkgreen") + 
  tm_shape(nearest_forest_connect) + tm_lines() + 
  tm_shape(df[1:10,]) + tm_dots("blue", size = 0.02)

```

```{r}
# Distance Calculation
nearest_forest <- nngeo::st_nn(df, forest_large, maxdist = 10000, k = 1, returnDist = TRUE)
length(nearest_forest$dist)
df <- df %>% mutate(forest_dist = round(as.numeric(nearest_forest$dist)))
```


```{r}
parks_area <- parks_raw$osm_polygons %>% st_area()
parks_large <- parks_raw$osm_polygons[parks_area > units::set_units(1000000, m^2), ]
parks_large
parks_large %>% tm_shape() + tm_fill("name")
parks_raw$osm_multipolygons %>% tm_shape() + tm_fill("black")

forest_raw$osm_multipolygons %>% tm_shape() + tm_fill("black")
```



# Save
```{r}
save(df, file = "rdata/prepared_data.Rdat")
```

