---
title: "Visualization"
author: "Tillmann Schwörer"
date: "WS 2020/21"
output: 
  html_document:
    toc: true
    toc_float: true
    df_print: paged
    code_folding: show  
    highlight: tango
    number_sections: true
---

```{r}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, fig.height = 5, fig.width = 12)
```

# Packages
```{r}
library(tidyverse)
library(sf)
library(tmap)
library(osmdata)
```

```{r}
load("data/prepared_data.Rdat")
```

# Visualization
## District level
```{r}
df %>% count(accommodates)

# Aggregates
vars <- c("n", "price", "size", "accomodates", "pool", ".resid")

df %>% 
  filter(accommodates==2) %>%
  group_by(name) %>% 
  summarise(across(all_of(vars), mean, na.rm=TRUE))


df_districts <- df %>% 
  filter(accommodates==2) %>%
  group_by(name) %>% 
  summarise(n = n(),
            price = round(mean(price, na.rm=TRUE)),
            stop_distance = round(mean(stop_dist, na.rm=TRUE)) 
            ) %>%
  st_drop_geometry()




districts %>% 
  inner_join(df_districts, by = "name") %>%
  tm_shape() +
  tm_fill("n", n = 10, convert2density = FALSE, style = "log10_pretty") +
  tm_borders() +
  tm_text(text = "price", size = 0.7)

districts %>% 
  inner_join(df_districts, by = "name") %>%
  tm_shape() +
  tm_fill("stop_distance", n = 10, style = "quantile") +
  tm_borders() +
  tm_text(text = "stop_distance", size = 0.7)


districts %>% 
  inner_join(df_districts, by = "name") %>%
  tm_shape() +
  tm_fill("price", n = 10, convert2density = FALSE) +
  tm_borders() +
  tm_dots(size = )
```

# Single object and amenities
```{r }
vars <- c("id", "listing_url", "price", "size", "neighbourhood_group_cleansed", "property_type", "room_type",
           "accommodates","wifi", "tv", "pool", "altbau", "cooking_basics", "bed_linens", "parking",
          "garden", "n_restaurants", "n_attractions", "stop_dist")

df <- df %>% select(all_of(vars)) %>% drop_na() %>% st_as_sf()
obj <- df %>% filter(id==8716837) %>% select(vars) %>% st_transform(3035)
View(obj)
obj_300 <- obj %>% st_buffer(dist = 300) 
obj_1000 <- obj_300 %>% st_buffer(dist = 700) 
test <- lm(price ~ size , df)
broom::augment_columns(test, data = df) %>% relocate(c(.fitted, .resid), .after = price) %>%View()
model.frame(test)

tmap_mode("view")
tm_shape(districts) + tm_fill(col = "name", legend.show = FALSE, group = 1) + 
  tm_borders(col = "black") +
  tm_shape(obj) + tm_dots(size = 0.1, id = "listing_url")
```

```{r}
districts <- districts %>% st_transform(3035)
restaurants <- restaurants %>% st_transform(3035) %>% mutate(type = "Restaurant")
attractions <- attractions %>% st_transform(3035) %>% mutate(type = "Attraction")
stops <- stops %>% st_transform(3035) %>% mutate(type = "Train/tram stop")

idx <- districts %>% st_intersects(obj_1000,sparse = FALSE) 
districts_subset <- districts[idx,]
idx <- restaurants %>% st_intersects(obj_1000, sparse = FALSE) 
restaurants_subset <- restaurants[idx,]
idx <- attractions %>% st_intersects(obj_1000, sparse = FALSE) 
attractions_subset <- attractions[idx,]
idx <- stops %>% st_intersects(obj_1000, sparse = FALSE) 
stops_subset <- stops[idx,]
subset <- list(restaurants_subset, attractions_subset, stops_subset) %>% bind_rows()
subset <- subset %>% select(name, cuisine, type, opening_hours)

tmap_mode("view")
tm_shape(districts_subset) + tm_fill(col = "name", alpha = 0.3, palette = "YlOrRd") + tm_shape(obj) + tm_dots("black", size = 0.1) +
  tm_shape(obj_300) + tm_borders("black", lwd = 1) + 
  tm_shape(obj_1000, is.master = TRUE) + tm_borders("black", lwd = 1) +
  tm_shape(subset) + tm_dots(col = "type", size = 0.05, palette = "Set1", 
                             popup.var = c("type", "cuisine", "opening_hours"))

```


